version: '3'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
  postgresql:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASS=admin
      - POSTGRES_DB=starter
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  data:
